# -*- coding: utf-8 -*-
"""Project103

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ah-T0TLiWV-CYB0haBr3K2xc_D7Hm_eN
"""

from google.colab import files
datatoload = files.upload()

import pandas as pd
data = [1,2,3,4,5]
pda = pd.DataFrame(data)
print(pda)

pip install plotly.express

import plotly.express as px
r = pd.read_csv("Copy+of+data+-+data.csv")
figure = px.scatter(r, x = "date", y = "cases", color = "country")
figure.show()